// Tab prop extraction (safe, behavior-preserving)
// Limits tab inputs to values this tab actually consumes.

export const createAccountsTabProps = (scope) => ({
  React: scope.React,
  supabase: scope.supabase,
  accountsSubTab: scope.accountsSubTab,
  calculateInvoiceData: scope.calculateInvoiceData,
  editingInvoiceId: scope.editingInvoiceId,
  editingInvoiceUpdatedAt: scope.editingInvoiceUpdatedAt,
  hasPendingChanges: scope.hasPendingChanges,
  formatCurrency: scope.formatCurrency,
  invoiceDateRange: scope.invoiceDateRange,
  invoiceManualItems: scope.invoiceManualItems,
  invoiceNumber: scope.invoiceNumber,
  invoiceRateOverrides: scope.invoiceRateOverrides,
  invoiceRoutesLoading: scope.invoiceRoutesLoading,
  invoiceViewMode: scope.invoiceViewMode,
  lastInteractionTime: scope.lastInteractionTime,
  savedInvoices: scope.savedInvoices,
  setDeleteConfirmModal: scope.setDeleteConfirmModal,
  setAccountsSubTab: scope.setAccountsSubTab,
  setEditingInvoiceId: scope.setEditingInvoiceId,
  setEditingInvoiceUpdatedAt: scope.setEditingInvoiceUpdatedAt,
  setInvoiceDateRange: scope.setInvoiceDateRange,
  setInvoiceManualItems: scope.setInvoiceManualItems,
  setInvoiceNumber: scope.setInvoiceNumber,
  setInvoiceRateOverrides: scope.setInvoiceRateOverrides,
  setInvoiceViewMode: scope.setInvoiceViewMode,
  setStoreRatesSearch: scope.setStoreRatesSearch,
  setSavedInvoices: scope.setSavedInvoices,
  storeRatesSearch: scope.storeRatesSearch,
  storesDirectory: scope.storesDirectory,
  updateStoreDirectory: scope.updateStoreDirectory,
  userName: scope.userName,
});
