// Drivers tab prop extraction (safe, behavior-preserving)
// Limits tab inputs to the values DriversTab actually consumes.

export const createDriversTabProps = (scope) => ({
  React: scope.React,
  driversSubTab: scope.driversSubTab,
  setDriversSubTab: scope.setDriversSubTab,
  driverStatusFilter: scope.driverStatusFilter,
  setDriverStatusFilter: scope.setDriverStatusFilter,
  driversDirectory: scope.driversDirectory,
  driverSortField: scope.driverSortField,
  setDriverSortField: scope.setDriverSortField,
  driverSortDirection: scope.driverSortDirection,
  setDriverSortDirection: scope.setDriverSortDirection,
  addDriverToDirectory: scope.addDriverToDirectory,
  setDriverPrintModal: scope.setDriverPrintModal,
  getExpiringDriverDocuments: scope.getExpiringDriverDocuments,
  setExpirationAlertsModal: scope.setExpirationAlertsModal,
  driverPrintModal: scope.driverPrintModal,
  driverPrintStatus: scope.driverPrintStatus,
  setDriverPrintStatus: scope.setDriverPrintStatus,
  driverPrintSortField: scope.driverPrintSortField,
  setDriverPrintSortField: scope.setDriverPrintSortField,
  driverPrintSortDirection: scope.driverPrintSortDirection,
  setDriverPrintSortDirection: scope.setDriverPrintSortDirection,
  driverPrintFields: scope.driverPrintFields,
  setDriverPrintFields: scope.setDriverPrintFields,
  escapeHtml: scope.escapeHtml,
  formatPhoneNumber: scope.formatPhoneNumber,
  licenseTypes: scope.licenseTypes,
  states: scope.states,
  trucksDirectory: scope.trucksDirectory,
  driverStatuses: scope.driverStatuses,
  updateDriverDirectory: scope.updateDriverDirectory,
  setDriverViewModal: scope.setDriverViewModal,
  removeDriverFromDirectory: scope.removeDriverFromDirectory,
  importDriversFromFile: scope.importDriversFromFile,
});
