// BOL generation module extracted from App.js
// Keeps print behavior identical while reducing App.js size.

export const generateBOLDocument=async ({route,routes,selectedDate,bolSettings,palletTypes,storesDirectory,escapeHtml})=>{const driverRoutes=routes.filter(r=>r.driver===route.driver);const routeNum=driverRoutes.indexOf(route)+1;const routeName=route.driver?route.driver+' #'+routeNum:'Route #'+routeNum;// Use selectedDate instead of today's date
const routeDate=new Date(selectedDate+'T12:00:00');const options={weekday:'long',year:'numeric',month:'long',day:'numeric'};const formattedDate=routeDate.toLocaleDateString('en-US',options);// Use BOL settings
const bolPalletColumns=bolSettings.palletColumns||9;const minEmptyRows=bolSettings.emptyRows||8;const palletColWidth=bolSettings.palletColumnWidth||28;const totalColWidth=bolSettings.totalColumnWidth||22;const fontTitle=bolSettings.fontSizeTitle||22;const fontPalletVal=bolSettings.fontSizePalletValue||12;const fontPalletType=bolSettings.fontSizePalletType||8;const fontTotals=bolSettings.fontSizeTotals||10;const fontBanner=bolSettings.fontSizeBanner||28;const bannerBorder=bolSettings.bannerBorder||5;const bannerPadding=bolSettings.bannerPadding||20;const fontStopNum=bolSettings.fontSizeStopNum||11;const fontStoreCode=bolSettings.fontSizeStoreCode||11;const fontStoreName=bolSettings.fontSizeStoreName||11;const fontAddress=bolSettings.fontSizeAddress||11;const mergeStyle=bolSettings.mergeIndicatorStyle||'arrow-orange';const printBackgrounds=bolSettings.printBackgroundGraphics!==false;const printHeaders=bolSettings.printHeadersFooters===true;// Generate merge indicator based on style
const getMergeIndicator=()=>{switch(mergeStyle){case'arrow-orange':return'<div style="position: absolute; right: -8px; top: 50%; transform: translateY(-50%); background: #ff9800; color: white; font-size: 10px; font-weight: bold; padding: 1px 3px; border-radius: 3px; z-index: 10; line-height: 1;">↔</div>';case'arrow-black':return'<div style="position: absolute; right: -8px; top: 50%; transform: translateY(-50%); background: #000; color: white; font-size: 10px; font-weight: bold; padding: 1px 3px; border-radius: 3px; z-index: 10; line-height: 1;">↔</div>';case'bracket':return'<div style="position: absolute; right: -10px; top: 50%; transform: translateY(-50%); border: 2px solid #000; font-size: 10px; font-weight: bold; padding: 0 4px; z-index: 10; background: white;">[ ]</div>';case'line-thick':return'<div style="position: absolute; right: -12px; top: 50%; transform: translateY(-50%); width: 14px; height: 4px; background: #000; z-index: 10;"></div>';case'line-double':return'<div style="position: absolute; right: -12px; top: 50%; transform: translateY(-50%); width: 14px; height: 6px; border-top: 2px solid #000; border-bottom: 2px solid #000; z-index: 10; background: white;"></div>';case'none':return'';default:return'<div style="position: absolute; right: -8px; top: 50%; transform: translateY(-50%); background: #ff9800; color: white; font-size: 10px; font-weight: bold; padding: 1px 3px; border-radius: 3px; z-index: 10; line-height: 1;">↔</div>';}};// Get merge legend symbol for legend display
const getMergeLegendSymbol=()=>{switch(mergeStyle){case'arrow-orange':return'↔';case'arrow-black':return'↔';case'bracket':return'[ ]';case'line-thick':return'';case'line-double':return'';default:return'↔';}};// Get merge legend style for legend display
const getMergeLegendStyle=()=>{switch(mergeStyle){case'arrow-orange':return'background: #ff9800; color: white; padding: 1px 4px; border-radius: 3px; font-weight: bold;';case'arrow-black':return'background: #000; color: white; padding: 1px 4px; border-radius: 3px; font-weight: bold;';case'bracket':return'border: 2px solid #000; padding: 0 4px; font-weight: bold;';case'line-thick':return'display: inline-block; width: 20px; height: 4px; background: #000; vertical-align: middle;';case'line-double':return'display: inline-block; width: 20px; height: 6px; border-top: 2px solid #000; border-bottom: 2px solid #000; vertical-align: middle;';default:return'background: #ff9800; color: white; padding: 1px 4px; border-radius: 3px; font-weight: bold;';}};// Calculate route totals using all pallet types
let routeTotalTC=0;let routeTotalPallets=0;const routeTotalsByType={};const typesUsedInRoute={};// Track which types are used (including pending)
palletTypes.forEach(pt=>{routeTotalsByType[pt.abbrev]=0;typesUsedInRoute[pt.abbrev]=false;});// First pass: find max pallet position with any value and which types are used
let maxPalletPosition=0;route.stores.forEach(store=>{const pallets=store.pallets||[];const types=store.palletTypes||[];pallets.forEach((p,idx)=>{// Check if this position has any value (number or "?")
if(p!==null&&p!==undefined&&p!==''){if(idx+1>maxPalletPosition)maxPalletPosition=idx+1;// Track that this type is used (for showing in totals header)
const pType=types[idx]||'FZ';const normalized=pType==='F'?'FZ':pType==='D'?'DR':pType==='S'?'SP':pType;typesUsedInRoute[normalized]=true;}// Count by type for totals (both numeric values AND "?" pending pallets)
if(p&&typeof p==='number'&&p>0||p==='?'){const pType=types[idx]||'FZ';const normalized=pType==='F'?'FZ':pType==='D'?'DR':pType==='S'?'SP':pType;routeTotalsByType[normalized]=(routeTotalsByType[normalized]||0)+1;routeTotalPallets++;}});routeTotalTC+=store.tc||0;pallets.forEach(p=>{if(p&&typeof p==='number'&&p>0)routeTotalTC+=p;});});// Filter to only pallet types that are used in this route (including pending)
const activePalletTypes=palletTypes.filter(pt=>typesUsedInRoute[pt.abbrev]);// Use the max pallet position found (show all columns that have values)
const actualPalletColumns=Math.max(1,maxPalletPosition);// Reset totals for second pass
routeTotalTC=0;routeTotalPallets=0;let routeTotalLinkedCount=0;// Track total merged pallets for route
palletTypes.forEach(pt=>{routeTotalsByType[pt.abbrev]=0;});// Build store rows
let storeRowsHTML='';route.stores.forEach((store,idx)=>{// Normalize store code for matching (handle string/number mismatch and whitespace)
const storeCode=String(store.code||'').trim();const dirStore=storesDirectory.find(s=>String(s.code||'').trim()===storeCode);let addressLine1=dirStore?dirStore.street:'';let addressLine2=dirStore?dirStore.city+', '+dirStore.state+' '+dirStore.zip:'';// ALWAYS prefer directory name over route store.name (route may have old/wrong data)
const storeName=dirStore?.name||store.name||'';const types=store.palletTypes||[];const links=store.palletLinks||[];const pallets=store.pallets||[];let palletCellsHTML='';for(let i=0;i<actualPalletColumns;i++){const val=pallets[i]||'';const type=types[i]||'FZ';const normalizedType=type==='F'?'FZ':type==='D'?'DR':type==='S'?'SP':type;const typeConfig=palletTypes.find(pt=>pt.abbrev===normalizedType)||palletTypes[0];const typeColor=typeConfig?typeConfig.color:'#666';// First column gets bold left border, last column gets bold right border
const leftBorder=i===0?'2px':'1px';const rightBorder=i===actualPalletColumns-1?'2px':'1px';// Check if next pallet is linked to this one
const nextIsLinked=links[i+1]||false;if(val){// Display "PLT" for pending pallets instead of "?"
const displayVal=val==='?'?'PLT':val;// Add arrow indicator if next pallet is linked to this one
const arrowIndicator=nextIsLinked&&pallets[i+1]?getMergeIndicator():'';palletCellsHTML+='<td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-left: '+leftBorder+' solid #000; border-right: '+rightBorder+' solid #000; padding: 2px; text-align: center; width: '+palletColWidth+'px; max-width: '+palletColWidth+'px; position: relative;"><div style="font-weight: bold; font-size: '+fontPalletVal+'px;">'+displayVal+'</div><div style="font-size: '+fontPalletType+'px; color: '+typeColor+'; font-weight: bold;">'+normalizedType+'</div>'+arrowIndicator+'</td>';}else{palletCellsHTML+='<td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-left: '+leftBorder+' solid #000; border-right: '+rightBorder+' solid #000; padding: 2px; text-align: center; width: '+palletColWidth+'px; max-width: '+palletColWidth+'px; color: #ccc;">-</td>';}}// Count pallets by type for this store
const storeCountsByType={};palletTypes.forEach(pt=>{storeCountsByType[pt.abbrev]=0;});let totalPallets=0;let linkedCount=0;// Track merged pallets
pallets.forEach((val,i)=>{// Count pallets (both numeric and pending "?")
if(val!==null&&val!==undefined&&val!==''){totalPallets++;// Check if this pallet is linked (merged with previous)
if(links[i]===true)linkedCount++;const type=types[i]||'FZ';const normalized=type==='F'?'FZ':type==='D'?'DR':type==='S'?'SP':type;if(storeCountsByType.hasOwnProperty(normalized)){storeCountsByType[normalized]++;}// Count both numeric values AND "?" pending pallets for route totals
if(typeof val==='number'&&val>0||val==='?'){if(routeTotalsByType.hasOwnProperty(normalized)){routeTotalsByType[normalized]++;}}}});// Calculate truck spots (merged pallets count as 1)
const truckSpots=totalPallets-linkedCount;routeTotalTC+=store.tc||0;routeTotalPallets+=truckSpots;// Use truck spots, not raw pallet count
routeTotalLinkedCount+=linkedCount;// Track for route total indicator
// Build type count cells for store row - only active pallet types
let typeCellsHTML='';activePalletTypes.forEach((pt,ptIdx)=>{const count=storeCountsByType[pt.abbrev]||0;typeCellsHTML+='<td style="border: 1px solid #000; padding: 2px; text-align: center; width: '+totalColWidth+'px; max-width: '+totalColWidth+'px; font-size: '+fontTotals+'px; color: '+(count?pt.color:'#ccc')+'; font-weight: bold;">'+(count||'-')+'</td>';});// Build notes display (if exists) - only Driver's Notes are printed
const storeNotes=store.driverNotes&&store.driverNotes.trim()?'<div style="color: #d32f2f; font-style: italic; font-size: 9px; margin-top: 2px;">⚠ '+escapeHtml(store.driverNotes)+'</div>':'';storeRowsHTML+='<tr style="height: 40px;">'+'<td style="border: 1px solid #000; border-left: 2px solid #000; padding: 4px; text-align: center; width: 20px; font-size: '+fontStopNum+'px;">'+(idx+1)+'</td>'+'<td style="border: 1px solid #000; padding: 4px; text-align: center; font-weight: bold; width: 35px; font-size: '+fontStoreCode+'px;">'+escapeHtml(store.code||'')+'</td>'+'<td style="border: 1px solid #000; padding: 4px; width: 100px; max-width: 100px; overflow: hidden; font-size: '+fontStoreName+'px;">'+escapeHtml(storeName)+storeNotes+'</td>'+'<td style="border: 1px solid #000; padding: 4px; width: 112px; max-width: 112px; overflow: hidden; font-size: '+fontAddress+'px; vertical-align: middle; text-align: center;">'+escapeHtml(addressLine1)+'<br>'+escapeHtml(addressLine2)+'</td>'+palletCellsHTML+'<td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-left: 2px solid #000; border-right: 1px solid #000; padding: 2px; text-align: center; font-weight: bold; width: '+totalColWidth+'px; font-size: '+fontTotals+'px;">'+(store.tc||'')+'</td>'+typeCellsHTML+'<td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-left: 1px solid #000; border-right: 2px solid #000; padding: 2px; text-align: center; font-weight: bold; width: '+totalColWidth+'px; max-width: '+totalColWidth+'px; font-size: '+fontTotals+'px;">'+(truckSpots||'')+'</td>'+'<td style="border: 1px solid #000; padding: 4px; width: 40px;"></td>'+'<td style="border: 1px solid #000; padding: 4px; width: 40px;"></td>'+'<td style="border: 1px solid #000; border-right: 2px solid #000; padding: 4px; width: 70px;"></td>'+'</tr>';});// No empty rows - only print actual stops
let headerCols='';for(let i=1;i<=actualPalletColumns;i++){const leftBorder=i===1?'2px':'1px';const rightBorder=i===actualPalletColumns?'2px':'1px';headerCols+='<th style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-left: '+leftBorder+' solid #000; border-right: '+rightBorder+' solid #000; padding: 4px; text-align: center; font-weight: bold; width: '+palletColWidth+'px;">'+i+'</th>';}// Build type header columns - only active pallet types
let typeHeaderCols='';activePalletTypes.forEach((pt,idx)=>{typeHeaderCols+='<th style="border: 1px solid #000; padding: 2px; text-align: center; width: '+totalColWidth+'px; max-width: '+totalColWidth+'px; font-size: '+fontTotals+'px; color: '+pt.color+'; font-weight: bold;">'+pt.abbrev+'</th>';});// Build route total type cells - only active pallet types
let routeTotalTypeCells='';activePalletTypes.forEach(pt=>{routeTotalTypeCells+='<td style="border-top: 2px solid #000; border-bottom: 2px solid #000; border-left: 1px solid #000; border-right: 1px solid #000; padding: 2px; text-align: center; width: '+totalColWidth+'px; max-width: '+totalColWidth+'px; font-size: '+fontTotals+'px; color: '+pt.color+'; font-weight: bold;">'+(routeTotalsByType[pt.abbrev]||0)+'</td>';});// BOL prints immediately without route calculations (use Route Card for that)
// Check if route is confirmed
const isRouteConfirmed=route.confirmed===true;// Watermark CSS for unconfirmed routes
const bolWatermarkCSS=!isRouteConfirmed?`
          .watermark {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 54px;
            font-weight: bold;
            color: rgba(255, 0, 0, 0.12);
            white-space: nowrap;
            z-index: 1000;
            pointer-events: none;
          }
          .watermark-banner {
            background: #c62828;
            color: white;
            text-align: center;
            padding: 8px 16px;
            font-size: 13px;
            font-weight: bold;
            margin-bottom: 10px;
            border-radius: 4px;
          }
          @media print {
            .watermark, .watermark-banner { 
              -webkit-print-color-adjust: exact !important;
              print-color-adjust: exact !important;
            }
          }
        `:'';// Watermark HTML
const bolWatermarkHTML=!isRouteConfirmed?`
          <div class="watermark">⚠ PENDING APPROVAL - DO NOT LOAD ⚠</div>
          <div class="watermark-banner">
            ⚠ WARNING: ROUTE NOT CONFIRMED - GET ADMIN APPROVAL BEFORE LOADING
          </div>
        `:'';const bolHTML='<!DOCTYPE html>'+'<html><head><title>BOL - '+routeName+' - '+formattedDate+'</title>'+'<style>'+bolWatermarkCSS+'@media print { '+'body { margin: 0; padding: 15px; '+(printBackgrounds?'-webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; color-adjust: exact !important;':'')+' } '+'@page { size: landscape; margin: '+(printHeaders?'0.5in 0.4in':'0.4in')+'; } '+(printBackgrounds?'* { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }':'')+' }'+'body { font-family: Arial, sans-serif; font-size: 11px; }'+'table { border-collapse: collapse; width: 100%; }'+'th { font-weight: bold; }'+'</style></head><body>'+bolWatermarkHTML+// Header Section
'<table style="margin-bottom: 15px; border: 2px solid #000;">'+'<tr>'+'<td style="padding: 10px; width: 35%; border-right: 2px solid #000;">'+'<div style="font-size: '+fontTitle+'px; font-weight: bold; letter-spacing: 1px;">'+bolSettings.documentTitle+'</div>'+'<div style="font-size: 13px; margin-top: 5px;">'+formattedDate+'</div>'+'</td>'+'<td style="padding: 10px; text-align: center; width: 12%; border-right: 2px solid #000;">'+'<div style="font-size: 10px; font-weight: bold; border-bottom: 1px solid #000; padding-bottom: 3px; margin-bottom: 5px;">ROUTE</div>'+'<div style="font-size: 14px; font-weight: bold;">'+routeName+'</div>'+'</td>'+'<td style="padding: 10px; text-align: center; width: 12%; border-right: 2px solid #000;">'+'<div style="font-size: 10px; font-weight: bold; border-bottom: 1px solid #000; padding-bottom: 3px; margin-bottom: 5px;">TRUCK #</div>'+'<div style="font-size: 18px; font-weight: bold;">'+(route.truck||'____')+'</div>'+(route.trailer?'<div style="font-size: 10px; font-weight: bold; margin-top: 4px; border-top: 1px solid #000; padding-top: 4px;">TRAILER: <span style="font-size: 18px;">'+route.trailer+'</span></div>':'')+'</td>'+'<td style="padding: 8px; width: 41%;">'+'<table style="width: 100%; font-size: '+fontTotals+'px;">'+'<tr><td style="padding: 2px;"><strong>Stores:</strong></td><td style="padding: 2px; text-align: right;">'+route.stores.length+'</td>'+'<td style="padding: 2px; padding-left: 8px;"><strong>Cases:</strong></td><td style="padding: 2px; text-align: right;">'+routeTotalTC+'</td></tr>'+'<tr><td style="padding: 2px;"><strong>Pallets:</strong></td><td style="padding: 2px; text-align: right;">'+routeTotalPallets+'</td></tr>'+'</table>'+'</td>'+'</tr></table>'+// Ship From / Driver Info
'<table style="margin-bottom: 12px;">'+'<tr>'+'<td style="width: 50%; vertical-align: top; padding-right: 10px;">'+'<table style="width: 100%; border: 1px solid #000;">'+'<tr><td style="border: 1px solid #000; padding: 6px; font-weight: bold; width: 80px;">SHIP FROM:</td>'+'<td style="border: 1px solid #000; padding: 6px;"><strong>'+escapeHtml(bolSettings.companyName)+'</strong> - '+escapeHtml(bolSettings.companyAddress)+'</td></tr>'+'<tr><td style="border: 1px solid #000; padding: 6px; font-weight: bold;">INSTRUCTIONS:</td>'+'<td style="border: 1px solid #000; padding: 6px;">'+escapeHtml(bolSettings.instructions)+'</td></tr>'+'</table></td>'+'<td style="width: 50%; vertical-align: top;">'+'<table style="width: 100%; border: 1px solid #000;">'+'<tr><td style="border: 1px solid #000; padding: 6px; font-weight: bold; width: 100px;">DRIVER NAME:</td>'+'<td style="border: 1px solid #000; padding: 6px; min-width: 150px;"></td>'+'<td style="border: 1px solid #000; padding: 6px; font-weight: bold; width: 80px;">SIGNATURE:</td>'+'<td style="border: 1px solid #000; padding: 6px; min-width: 120px;"></td></tr>'+'<tr><td style="border: 1px solid #000; padding: 6px; font-weight: bold;">DEPARTURE:</td>'+'<td style="border: 1px solid #000; padding: 6px;"></td>'+'<td style="border: 1px solid #000; padding: 6px; font-weight: bold;">RETURN:</td>'+'<td style="border: 1px solid #000; padding: 6px;"></td></tr>'+'</table></td>'+'</tr></table>'+// Pallet Type Legend - Larger, above table with colored boxes
'<div style="font-size: 10px; color: #333; text-align: center; padding: 6px 8px; background: #f5f5f5; border-bottom: 2px solid #000; margin-top: 8px; margin-bottom: 0;">'+'<strong>PALLET TYPES:</strong> &nbsp;&nbsp;'+activePalletTypes.map(pt=>'<span style="display: inline-block; width: 12px; height: 12px; background: '+pt.color+'; border-radius: 2px; vertical-align: middle;"></span> '+pt.abbrev+' = '+pt.name).join(' &nbsp;&nbsp;')+(mergeStyle!=='none'?' &nbsp;&nbsp;|&nbsp;&nbsp; <span style="'+getMergeLegendStyle()+'">'+getMergeLegendSymbol()+'</span> = Merged Pallets':'')+'</div>'+// Main Delivery Table
'<table style="margin-bottom: 12px; border: 2px solid #000;">'+'<thead>'+'<tr>'+'<th rowspan="2" style="border: 2px solid #000; padding: 4px; width: 20px;">Stop #</th>'+'<th rowspan="2" style="border: 2px solid #000; padding: 4px; width: 35px;">Store #</th>'+'<th rowspan="2" style="border: 2px solid #000; padding: 4px; width: 100px;">Store Name</th>'+'<th rowspan="2" style="border: 2px solid #000; padding: 4px; width: 112px;">Address</th>'+'<th colspan="'+actualPalletColumns+'" style="border: 2px solid #000; padding: 4px; text-align: center;">Cases per Pallet</th>'+'<th colspan="'+(activePalletTypes.length+2)+'" style="border: 2px solid #000; padding: 4px; text-align: center;">Totals</th>'+'<th rowspan="2" style="border: 2px solid #000; padding: 4px; width: 40px;">Time In</th>'+'<th rowspan="2" style="border: 2px solid #000; padding: 4px; width: 40px;">Time Out</th>'+'<th rowspan="2" style="border: 2px solid #000; padding: 4px; width: 70px;">Receiver</th>'+'</tr>'+'<tr>'+headerCols+'<th style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-left: 2px solid #000; border-right: 1px solid #000; padding: 2px; text-align: center; width: '+totalColWidth+'px; font-size: '+fontTotals+'px;">TC</th>'+typeHeaderCols+'<th style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-left: 1px solid #000; border-right: 2px solid #000; padding: 2px; text-align: center; width: '+totalColWidth+'px; max-width: '+totalColWidth+'px; font-size: '+fontTotals+'px;">PLT</th>'+'</tr>'+'</thead>'+'<tbody>'+storeRowsHTML+'</tbody>'+'<tfoot><tr style="font-weight: bold;">'+'<td colspan="4" style="border: 2px solid #000; padding: 6px; text-align: right;">ROUTE TOTALS:</td>'+'<td colspan="'+actualPalletColumns+'" style="border: 2px solid #000;"></td>'+'<td style="border-top: 2px solid #000; border-bottom: 2px solid #000; border-left: 2px solid #000; border-right: 1px solid #000; padding: 2px; text-align: center; width: '+totalColWidth+'px; font-size: '+fontTotals+'px;">'+routeTotalTC+'</td>'+routeTotalTypeCells+'<td style="border-top: 2px solid #000; border-bottom: 2px solid #000; border-left: 1px solid #000; border-right: 2px solid #000; padding: 2px; text-align: center; width: '+totalColWidth+'px; max-width: '+totalColWidth+'px; font-size: '+fontTotals+'px;">'+routeTotalPallets+'</td>'+'<td colspan="3" style="border: 2px solid #000;"></td>'+'</tr></tfoot>'+'</table>'+// Bottom Section - Notes, Inspection, Signature
'<table style="width: 100%;">'+'<tr>'+(// Notes Column (conditional)
bolSettings.showNotesSection?'<td style="width: 35%; vertical-align: top; padding-right: 10px;">'+'<table style="width: 100%; border: 1px solid #000; height: 100%;">'+'<tr><td style="border: 1px solid #000; padding: 6px; font-weight: bold;">NOTES & CONTACT</td></tr>'+'<tr><td style="border: 1px solid #000; padding: 8px; vertical-align: top;">'+'Any problems, call: <strong>'+escapeHtml(bolSettings.contactName)+' '+escapeHtml(bolSettings.contactPhone)+'</strong><br><br>'+'<div style="margin-top: 10px; font-weight: bold; border: 1px solid #000; padding: 5px; text-align: center;">'+'DRIVER MUST PICK UP EMPTY PALLETS</div>'+(// P/U at Paris Baguette Notice inside Notes box
route.pickupAtPB?'<div style="margin-top: 10px; padding: '+bannerPadding+'px; background: #ffeb3b; border: '+bannerBorder+'px solid #d32f2f; border-radius: 4px; text-align: center;">'+'<span style="font-size: '+fontBanner+'px; font-weight: bold; color: #b71c1c;">📦 P/U AT PARIS BAGUETTE 📦</span>'+'</div>':'')+'</td></tr></table></td>':'')+(// Load Inspection Column (conditional)
bolSettings.showInspectionSection?'<td style="width: 35%; vertical-align: top; padding-right: 10px;">'+'<table style="width: 100%; border: 1px solid #000;">'+'<tr><td colspan="2" style="border: 1px solid #000; padding: 6px; font-weight: bold; text-align: center;">LOAD INSPECTION</td></tr>'+'<tr><td style="border: 1px solid #000; padding: 5px; width: 70%;">Clean / Pest Free</td><td style="border: 1px solid #000; padding: 5px; text-align: center; width: 30%;"> OK</td></tr>'+'<tr><td style="border: 1px solid #000; padding: 5px;">Odor Free</td><td style="border: 1px solid #000; padding: 5px; text-align: center;"> OK</td></tr>'+'<tr><td style="border: 1px solid #000; padding: 5px;">Products on Pallets</td><td style="border: 1px solid #000; padding: 5px; text-align: center;"> OK</td></tr>'+'<tr><td style="border: 1px solid #000; padding: 5px;">Lights Shielded</td><td style="border: 1px solid #000; padding: 5px; text-align: center;"> OK</td></tr>'+'<tr><td style="border: 1px solid #000; padding: 5px;">Temp: Start____  Mid____  End____</td><td style="border: 1px solid #000; padding: 5px; text-align: center;"> OK</td></tr>'+'</table></td>':'')+(// Signatures Column (conditional)
bolSettings.showSignatureSection?'<td style="width: 30%; vertical-align: top;">'+'<table style="width: 100%; border: 1px solid #000;">'+'<tr><td colspan="2" style="border: 1px solid #000; padding: 6px; font-weight: bold; text-align: center;">VERIFICATION</td></tr>'+'<tr><td style="border: 1px solid #000; padding: 5px; width: 40%;">Loaded By:</td><td style="border: 1px solid #000; padding: 5px;"></td></tr>'+'<tr><td style="border: 1px solid #000; padding: 5px;">Checked By:</td><td style="border: 1px solid #000; padding: 5px;"></td></tr>'+'<tr><td style="border: 1px solid #000; padding: 5px;">Seal #:</td><td style="border: 1px solid #000; padding: 5px;"></td></tr>'+'<tr><td style="border: 1px solid #000; padding: 8px; font-weight: bold;" colspan="2">Driver Signature:</td></tr>'+'<tr><td style="border: 1px solid #000; padding: 15px;" colspan="2"></td></tr>'+'</table></td>':'')+'</tr></table>'+// Footer
'<div style="margin-top: 10px; text-align: center; font-size: 9px; color: #666; border-top: 1px solid #ccc; padding-top: 5px;">'+escapeHtml(bolSettings.companyName)+' - '+escapeHtml(bolSettings.companyAddress)+' - Phone: '+escapeHtml(bolSettings.contactPhone)+'</div>'+'<scr'+'ipt>window.onload = function() { window.print(); }</scr'+'ipt>'+'</body></html>';const printWindow=window.open('','_blank');printWindow.document.write(bolHTML);printWindow.document.close();};
